package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func Test_generate(t *testing.T) {

	t.Run("success-1", func(t *testing.T) {
		src := `
master-key: 32e41268f19aafee9a21de86b3779f5cb9a38204fa81b65703f0e152b2601588d8579443bcb0999f361fb53fbf9dc57035dcee01fba6b7d4fe07d76557ae31d9 # head -c 64 /dev/urandom | xxd -ps
jwt-secret: GGUlF5jvRXwlVSqlbdpojwnVPNyStlMcGtFNRsrPCF15Q+6Ker6AgBJjEvzB3XILFE4Njuo2hDiKX4PRbs+Uxg== # head -c 64 /dev/urandom | base64
server: 
  listen: :8080
ingest:
  chan-size: 100
log-level: debug
consumer-jwt:
  iss: dTAL519o69-local
  type: logging-consumer-token
  version: 1
`

		expected := `// generated by viper-const-from-yaml.test
const (
	ConsumerJwtIss     = "consumer-jwt.iss"
	ConsumerJwtType    = "consumer-jwt.type"
	ConsumerJwtVersion = "consumer-jwt.version"
	IngestChanSize     = "ingest.chan-size"
	JwtSecret          = "jwt-secret"
	LogLevel           = "log-level"
	MasterKey          = "master-key"
	ServerListen       = "server.listen"
)
`

		d, err := generate([]byte(src))
		assert.NoError(t, err)

		assert.Equal(t, expected, string(d))

	})

}
